import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import './Home.css';

const Home = () => {
  const navigate = useNavigate();
  const [userId, setUserId] = useState('');
  const [selectedTechnology, setSelectedTechnology] = useState('');

  const technologies = [
    { name: 'MERN', color: '#61dafb', description: 'MongoDB, Express, React, Node.js' },
    { name: 'C++', color: '#00599c', description: 'Object-oriented programming and algorithms' },
    { name: 'Java', color: '#ed8b00', description: 'Enterprise applications and Spring Framework' }
  ];

  const handleStartInterview = async () => {
    if (!userId.trim()) {
      alert('Please enter your name or user ID');
      return;
    }

    if (!selectedTechnology) {
      alert('Please select a technology');
      return;
    }

    // Store userId in localStorage
    localStorage.setItem('userId', userId);
    
    navigate(`/interview/${selectedTechnology}`);
  };

  return (
    <div className="home">
      <div className="home-container">
        <div className="home-header">
          <h1>AI Mock Interview Prep</h1>
          <p>Practice technical interviews for MERN, C++, and Java with AI-powered feedback</p>
        </div>

        <div className="home-card">
          <div className="input-group">
            <label htmlFor="userId">Enter Your Name or ID:</label>
            <input
              type="text"
              id="userId"
              className="input"
              placeholder="e.g., Karan"
              value={userId}
              onChange={(e) => setUserId(e.target.value)}
            />
          </div>

          <div className="technology-selection">
            <h2>Select Technology:</h2>
            <div className="technology-grid">
              {technologies.map((tech) => (
                <div
                  key={tech.name}
                  className={`technology-card ${selectedTechnology === tech.name ? 'selected' : ''}`}
                  onClick={() => setSelectedTechnology(tech.name)}
                  style={{ borderColor: selectedTechnology === tech.name ? tech.color : '#e0e0e0' }}
                >
                  <div className="tech-icon" style={{ color: tech.color }}>
                    {tech.name}
                  </div>
                  <h3>{tech.name}</h3>
                  <p>{tech.description}</p>
                </div>
              ))}
            </div>
          </div>

          <button
            className="button button-primary"
            onClick={handleStartInterview}
          >
            Start Interview
          </button>

          <div className="home-actions">
            <button
              className="button button-secondary"
              onClick={() => navigate('/history')}
            >
              View History
            </button>
          </div>
        </div>

        <div className="features">
          <h2>Features</h2>
          <div className="features-grid">
            <div className="feature-card">
              <div className="feature-icon">🤖</div>
              <h3>AI-Powered Questions</h3>
              <p>Get personalized interview questions generated by AI</p>
            </div>
            <div className="feature-card">
              <div className="feature-icon">💡</div>
              <h3>Instant Feedback</h3>
              <p>Receive detailed feedback and scoring for each answer</p>
            </div>
            <div className="feature-card">
              <div className="feature-icon">📊</div>
              <h3>Track Progress</h3>
              <p>Monitor your interview performance over time</p>
            </div>
            <div className="feature-card">
              <div className="feature-icon">🎯</div>
              <h3>Multiple Technologies</h3>
              <p>Practice interviews for MERN, C++, and Java</p>
            </div>
            <div className="feature-card">
              <div className="feature-icon">🎤</div>
              <h3>Voice Input</h3>
              <p>Answer questions using your microphone with speech recognition</p>
            </div>
          </div>
        </div>

        <div className="footer">
          <p>Developed by <a href="https://github.com/Karansinghpal" target="_blank" rel="noopener noreferrer" className="github-link">Karan Singh Pal</a></p>
          <a href="https://github.com/Karansinghpal" target="_blank" rel="noopener noreferrer" className="github-icon" title="View on GitHub">
            <svg width="24" height="24" viewBox="0 0 24 24" fill="currentColor">
              <path d="M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z"/>
            </svg>
          </a>
        </div>
      </div>
    </div>
  );
};

export default Home;

